Particular/RepoStandards

.gitignore

[Rider](https://blog.jetbrains.com/dotnet/2016/01/13/project-rider-a-csharp-ide/) is an upcoming .NET IDE from JetBrains. As all other IntelliJ-based IDEs, it creates workspace files that should be ignored. This PR adds files specific to Rider to .gitignore.

Adding JetBrains Rider (.NET IDE) specific files to .gitignore

---

src/RepoName.sln.DotSettings

Updates the repo standards to exclude the App_Packages from code analysis
more info https://github.com/Particular/NServiceBus.StructureMap/pull/33
thanks @HEskandari for fixing it
@Particular/nservicebus-maintainers please review

Excluding app_packages from analysis

---

.gitattributes

Setting merge=union for project files just ends up causing worse problems. If a merge conflict in a project file occurs, you just end up with both versions in the file instead, which is never what you want.
See http://haacked.com/archive/2014/04/16/csproj-merge-conflicts/ for more info.
CC: @timbussmann

Remove merge=union from .gitattributes

---

src/Directory.Build.props

These changes will allow us to get deterministic builds when we build on CI.
The `SourceRoot` items are to ensure that the source path mapping works properly. This features anonymizes the paths names for source files.
AFAIK this should be safe to enable for all repos that are already syncing this file.

Enable deterministic CI builds

---

src/Directory.Build.props

Tooling, eg. visual studio, MSBuild, already selects the appropriate language version depending on the target frameworks used so there is no need for us to force it.

Adjust standards to no longer force C# 7.3 and instead rely on tooling defaults

---

.github/stale.yaml

As per the work in https://github.com/Particular/KeepTheLightsOn.LowPriority/issues/127 and RFC in  https://github.com/Particular/KeepTheLightsOn/pull/606 this add Stale bot config to the Repostandards.

Add stalebot config

---

src/.editorconfig

https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1068
I tested this change locally by editing a `.editorconfig` and moving a token param, and the diagnostic was shown.

add CA1068 — CancellationToken parameters must come last

---

.github/workflows/virus-scan.yml

Publishing a release triggers a workflow that:
1. Installs ClamAV using apt-get
2. Updates the virus definition database
3. Gets the release from GitHub and downloads all of the assets to a folder, including the zipball and tarball.
4. Runs ClamAV on the folder
5. If a virus is detected, alerts us on Slack
6. Updates the GitHub release markdown by adding the virus scan summary at the bottom

Add workflow to virus-scan releases on publish

---

src/.editorconfig

- [CA1710: Identifiers should have correct suffix](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1710)
- [CA1711: Identifiers should not have incorrect suffix](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1711)

enable CA1710 and CA1711

---

.github/workflows/virus-scan.yml

Uses action at https://github.com/Particular/virus-scan-action @ main, so it can be distributed to all repos and never needs to be updated for versioning purposes. The virus-scan-action repo absorbs the dependabot versioning updates to [actions/github-script](https://github.com/actions/github-script), which are tested using that repo's CI, and when merged are used by all repos immediately.
Note: It is possible that Dependabot doesn't yet know how to update versions on an action.yml, but if so we can still periodically perform and test those updates ourselves.

Use centralized virus-scan-action

---

.github/dependabot.yml

* Standardizes what's going on with the labels, allows us to filter on:
* All Dependabot with [label:dependencies](https://github.com/pulls?q=is%3Aopen+is%3Apublic+is%3Apr+org%3AParticular+archived%3Afalse+label%3Adependencies
* All GH Actions updates with [label:dependencies label:github_actions](https://github.com/pulls?q=is%3Aopen+is%3Apublic+is%3Apr+org%3AParticular+archived%3Afalse+label%3Adependencies+label%3Agithub_actions)
* Only NuGet updates with [label:dependencies label:NuGet](https://github.com/pulls?q=is%3Aopen+is%3Apublic+is%3Apr+org%3AParticular+archived%3Afalse+label%3Adependencies+label%3ANuGet+)
* Should fix the weirdness going on in the [ServicePulse PRs](https://github.com/Particular/ServicePulse/pulls) with the label `Has external dependency which is coming from who …

Updates to dependabot config

---

LICENSE.md

In order to address https://github.com/Particular/CustomerSuccess/issues/1930
The language proposed here would cover all code in all the repositories in our GitHub organization, including those which do not use the name NServiceBus in them, like ServiceInsight or ServicePulse.

Clarifying ambiguity of the term "NServiceBus" in our repositories' License file

---

nuget.config
src/Directory.Build.props

These changes are required to use NuGet central package management, which has been enabled in ServiceConrol so far.

Changes for central package management

---

.github/ISSUE_TEMPLATE/config.yml

Added a config.yml file that adds links to ParitcularDiscuss where users can ask a question, and other support options when opening an issue.

Add links to additional resources to issue templates

---

src/Directory.Build.props

This change maintains the default `AnalysisLevel` of 5.0, but lets us customize it in Custom.Build.props.
This ensures that existing branches won't get new analyzer errors just by merging this change, but on a per-repo and per-branch basis, we can start increasing the level to enable the new analyzers that have shipped in SDKs past .NET 5.

Let AnalysisLevel be customized

---

src/.editorconfig

This analyzer has started flagging things that can be changed based on new C# 12 language features, but the matching VS fixer hasn't shipped yet.
This PR turns this into a suggestion for now to unblock repos. Once we have the fixer, we can look into changing the code and then turning this back into an error.

Make IDE0028 a suggestion

---

src/.editorconfig

This ensures that `.props` and `.targets` files get the same formatting rules that we want for other XML "project files".

Add props and targets to "project file" formatting

---

nuget.config

This adds a `local packages` package source mapping so that you can have a local folder set up as package source. The only requirement is that the source needs to be named 'local packages` (case sensitive):

Add local packages feed to package source mappings

---

src/Directory.Build.props

* Particular.Analyzers 2.1.0 featuring new new analyzers:
* https://github.com/Particular/Particular.Analyzers/pull/272
* https://github.com/Particular/Particular.Analyzers/pull/278
* Treat warnings as errors only in non-Debug builds for better developer productivity as suggested in https://twitter.com/STeplyakov/status/1765100971255116284
* Better notification for CVEs, will get notified for transitive dependencies as well, as suggested in https://twitter.com/SimonCropp/status/1772059185104249303

Particular.Analyzers 2.1.0 and other settings

---

src/.editorconfig

The 8.0.300 SDK is causing new errors for `IDE0100`, but 8.0.300 doesn't work properly with Visual Studio 17.9.7. With it installed, the SDK analyzers don't work. For example:
```
The analyzer assembly 'C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CodeStyle.dll' references version '4.10.0.0' of the compiler, which is newer than the currently running version '4.9.0.0'.	ServiceControl.Audit.Persistence.SagaAudit	C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CodeStyle.dll
```
Until we can run the analzyers inside of Visual Studio, there's no easy way to fix up the code that is triggering `IDE0100`.
This PR turns `IDE0100` into a suggestion as a workaround for now.

Make IDE0100 a suggestion for now

---

.github/dependabot.yml
README.md
src/Directory.Build.props
src/Directory.Build.targets
src/msbuild/AutomaticVersionRanges.targets
src/msbuild/ConvertToVersionRange.cs

This PR makes changes to prepare for handling vulnerabilities reported by NuGet's security audit feature.
- We're now explicitly setting `NuGetAuditMode` in `Directory.Build.props` to `all` to match the default value coming in the 9.0.100 SDK. This value can be set in `Custom.Build.props` to override the value globally, something we might end up needing to do on older release branches, for example.
- To make it easier to update `PackageReference` versions and to eliminate the need for duplicate references in test projects, the automatic version ranges feature added here will automatically create the version ranges for any packages that are created.
- Dependabot stopped considering the Feedz feed for its package updating portion of its process, so packages that are only on Feedz weren't …

NuGet updates

---

.github/workflows/nuget-audit.yml

This PR updates the nuget-audit.yml to use [a reusable workflow in the shared-workflows repository](https://github.com/Particular/shared-workflows/blob/main/.github/workflows/nuget-audit.yml).
This will mean that dependabot updates will happen in the shared-workflows repository, and this workflow will see that update as soon as it is merged.
[Example run from ReleaseSandbox](https://github.com/Particular/ReleaseSandbox/actions/runs/12798382723/job/35682295636).

Simplify nuget-audit.yml

---

.github/workflows/code-analysis.yml

Adds code analysis to the push triggers on default/release branches, as well as workflow_dispatch. The latter allows it to be invoked centrally on all release branches in order to get feedback on what works where. After the code analysis action is fixed up to work everywhere and everything is green, a `pull_request` trigger can be added.

Distribute code analysis workflow
